- name: check idempotency
  become: yes                            #give root permissions to create user
  hosts: local
  connection: local
  tasks:
  - name: user creation
    ansible.builtin.user:            #ansible builting user module to manage user specific things.
      name: johnd                     #creatting the user john without using useradd john like ansible.builtin.command module